# Generated by Django 4.1.2 on 2022-12-19 19:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deuldou',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 12, 19, 20, 22, 46, 12780))),
                ('nom', models.CharField(max_length=100)),
                ('jour', models.DateTimeField(default=datetime.datetime(2022, 12, 19, 20, 22, 46, 12780))),
                ('adresse', models.TextField()),
                ('nbre_min', models.IntegerField(default=0)),
                ('createur_participe', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deuldous_crees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('est_inscrit', models.BooleanField(default=False)),
                ('visible', models.BooleanField(default=True)),
                ('prenom', models.CharField(blank=True, max_length=100, null=True)),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('commentaire', models.TextField(null=True)),
                ('deuldou', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='deuldou.deuldou')),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Statut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('is_checked', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etiquettes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Liste_invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listes_invitation', to=settings.AUTH_USER_MODEL)),
                ('invites', models.ManyToManyField(to='deuldou.invite')),
            ],
        ),
        migrations.AddField(
            model_name='invite',
            name='statut',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='deuldou.statut'),
        ),
        migrations.AddField(
            model_name='invite',
            name='tags',
            field=models.ManyToManyField(to='deuldou.tag'),
        ),
        migrations.AddField(
            model_name='invite',
            name='utilisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='invite',
            constraint=models.UniqueConstraint(fields=('deuldou', 'email'), name='invitation unique'),
        ),
    ]
