# Generated by Django 4.1.2 on 2023-04-16 18:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deuldou', '0003_alter_deuldou_created_at_alter_deuldou_jour_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='pseudo',
            new_name='nom',
        ),
        migrations.AlterField(
            model_name='deuldou',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 16, 20, 14, 51, 76134)),
        ),
        migrations.AlterField(
            model_name='deuldou',
            name='jour',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 16, 20, 14, 51, 76134)),
        ),
        migrations.CreateModel(
            name='Liste_contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liste_contacts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('nom', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
