# Generated by Django 4.1.2 on 2023-04-16 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deuldou', '0004_rename_pseudo_participant_nom_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='liste_contacts',
            options={'ordering': ['nom']},
        ),
        migrations.AddField(
            model_name='liste_contacts',
            name='contacts',
            field=models.ManyToManyField(to='deuldou.contact'),
        ),
        migrations.AlterField(
            model_name='deuldou',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 16, 20, 58, 22, 116859)),
        ),
        migrations.AlterField(
            model_name='deuldou',
            name='jour',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 16, 20, 58, 22, 116859)),
        ),
        migrations.AlterField(
            model_name='participant',
            name='nom',
            field=models.CharField(default='defaut', max_length=200),
            preserve_default=False,
        ),
    ]
