# Generated by Django 4.1.2 on 2023-04-30 17:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deuldou', '0005_alter_liste_contacts_options_liste_contacts_contacts_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deuldou',
            old_name='adresse',
            new_name='lieu',
        ),
        migrations.RemoveField(
            model_name='deuldou',
            name='createur_participe',
        ),
        migrations.AddField(
            model_name='deuldou',
            name='heure_debut',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='deuldou',
            name='heure_fin',
            field=models.TimeField(blank=True, default='00:00'),
        ),
        migrations.AlterField(
            model_name='deuldou',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 30, 17, 9, 27, 83191, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='deuldou',
            name='jour',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='participant',
            name='nom',
            field=models.CharField(default='anonyme', max_length=200),
        ),
        migrations.AlterField(
            model_name='participant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to=settings.AUTH_USER_MODEL),
        ),
    ]
