# Generated by Django 4.1.2 on 2023-05-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deuldou', '0007_alter_deuldou_created_at_alter_deuldou_heure_fin_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='participant',
            name='participation unique',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='user',
        ),
        migrations.AddField(
            model_name='participant',
            name='email',
            field=models.EmailField(default='seb@gmail.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participant',
            name='commentaire',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='nom',
            field=models.CharField(max_length=150),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(fields=('rdv', 'email'), name='participation unique'),
        ),
    ]
