# Generated by Django 4.1.2 on 2023-05-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deuldou', '0009_alter_contact_email_alter_contact_nom'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contact',
            name='contact unique',
        ),
        migrations.RemoveConstraint(
            model_name='participant',
            name='participation unique',
        ),
        migrations.AddField(
            model_name='deuldou',
            name='createur_participe',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=150),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(fields=('user', 'email'), name='contact unique', violation_error_message='Ce contact existe déjà'),
        ),
        migrations.AddConstraint(
            model_name='liste_contacts',
            constraint=models.UniqueConstraint(fields=('user', 'nom'), name='liste unique', violation_error_message='Cette liste existe déjà'),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(fields=('rdv', 'email'), name='participation unique', violation_error_message='Ce participant existe déjà'),
        ),
    ]
