# Generated by Django 4.1.2 on 2023-08-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deuldou', '0011_remove_deuldou_createur_participe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deuldou',
            name='heure_fin',
            field=models.TimeField(default='00:00', null=True),
        ),
    ]
