# Generated by Django 4.1.2 on 2023-10-16 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deuldou', '0012_alter_deuldou_heure_fin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liste_invitation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='liste_invitation',
            name='invites',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='user',
        ),
        migrations.AlterField(
            model_name='deuldou',
            name='heure_fin',
            field=models.TimeField(blank=True, default='00:00'),
        ),
        migrations.DeleteModel(
            name='Invite',
        ),
        migrations.DeleteModel(
            name='Liste_invitation',
        ),
        migrations.DeleteModel(
            name='Statut',
        ),
        migrations.DeleteModel(
            name='Utilisateur',
        ),
    ]
